### ISSUE TITLE
The compilation fails on "configuration_file.cpp:444:39: error: cannot convert ‘std::basic_istream<char>’ to ‘bool’ in initialization"

### ISSUE THREAD

**Issue by goupildb** [j-jorge/libclaw#2]
La Compilation échoue sur:
(...)
[  2%] Built target claw_dynamic_library
[  3%] Building CXX object CMakeFiles/claw_configuration_file.dir/claw/code/configuration_file.cpp.o
/mnt/DDprc/Download/libclaw-master/claw/code/configuration_file.cpp: In member function ‘bool claw::configuration_file::get_line(std::istream&, const claw::configuration_file::syntax_description&, std::__cxx11::string&) const’:
/mnt/DDprc/Download/libclaw-master/claw/code/configuration_file.cpp:444:39: error: cannot convert ‘std::basic_istream<char>’ to ‘bool’ in initialization
   bool result = text::getline(is, line);
                                       ^
CMakeFiles/claw_configuration_file.dir/build.make:62 : la recette pour la cible « CMakeFiles/claw_configuration_file.dir/claw/code/configuration_file.cpp.o » a échouée
make[2]: *** [CMakeFiles/claw_configuration_file.dir/claw/code/configuration_file.cpp.o] Erreur 1
(...)

**Comment by j-jorge** [comment]
C'est maintenant corrigé dans `e00d4b68ebfcd1b0f1e4c4653b3d29f579027f8e`.
